synergyway/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'', include('user_manager.urls'))
]

user_manager/urls.py
from django.conf.urls import url

from user_manager import views
from user_manager.views import delete_user, courses

urlpatterns = (
    url(r'^$', views.user_list, name='user_list'),
    url(r'^create_user/$', views.create_user, name='create_user'),
    url(r'^edit_user/(?P<pk>\d+)/$', views.edit_user, name='edit_user'),
    url(r'^delete_user/(?P<pk>\d+)/$', delete_user, name='delete_user'),
    url(r'^courses/$', courses, name='courses'),
)

user_manager/forms.py
from django import forms

from user_manager.utils import get_all_curses


class CreateUserForm(forms.Form):
    STATUS = (
        ('', 'Inactive'),
        (1, 'Active')
    )
    name = forms.CharField(max_length=244)
    email = forms.EmailField()
    phone = forms.RegexField(regex=r'^\+?1?\d{9,15}$', required=False, error_message=(
        "Format phone number : '+999999999'."" Up to 15 digits allowed."))
    mobile = forms.RegexField(regex=r'^\+?1?\d{9,15}$', required=False, error_message=(
        "Format phone number : '+999999999'."" Up to 15 digits allowed."), label='Mobile phone')
    status = forms.ChoiceField(required=False, choices=STATUS)


class EditUserForm(forms.Form):
    STATUS = (
        ('', 'Inactive'),
        (1, 'Active')
    )

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields['courses'] = forms.MultipleChoiceField(required=False, choices=get_all_curses())
        self.fields['name'].widget.attrs['readonly'] = True
    name = forms.CharField(max_length=244)
    email = forms.EmailField()
    phone = forms.RegexField(regex=r'^\+?1?\d{9,15}$', required=False, error_message=(
        "Format phone number : '+999999999'."" Up to 15 digits allowed."))
    mobile = forms.RegexField(regex=r'^\+?1?\d{9,15}$', required=False, error_message=(
        "Format phone number : '+999999999'."" Up to 15 digits allowed."), label='Mobile phone')
    status = forms.ChoiceField(required=False, choices=STATUS)
    courses = forms.MultipleChoiceField()

user_manager/views.py
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.views.decorators.http import require_GET

from user_manager.forms import CreateUserForm, EditUserForm
from user_manager.utils import get_user_list, new_user, get_user_data, change_user, remove_user, get_course_list


@require_GET
def user_list(request):
    page = request.GET.get('page', 1)
    search = request.GET.get('search', '')
    if 'row_count' in request.COOKIES:
        row_count = request.COOKIES.get('row_count')
    else:
        row_count = 10
    paginator, users = get_user_list(page, row_count, search)
    context = {'users': users, 'paginator': paginator, 'search': search, 'row_count': row_count}
    return render_to_response('user_manager/user_list.html', context)


def create_user(request):
    if request.method == 'GET':
        form = CreateUserForm()
        context = {'form': form}
        return render_to_response('user_manager/create_user.html', context)
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if not form.is_valid():
            return HttpResponseBadRequest(form.errors.as_json())
        new_user(form.cleaned_data)
        return HttpResponse('')


def edit_user(request, pk):
    if request.method == 'GET':
        user_data = get_user_data(pk)
        form = EditUserForm(user_data)
        context = {'form': form}
        return render_to_response('user_manager/edit_user.html', context)
    if request.method == 'POST':
        form = EditUserForm(request.POST)
        if not form.is_valid():
            return HttpResponseBadRequest(form.errors.as_json())
        change_user(pk, form.cleaned_data)
        return HttpResponse('')


def delete_user(request, pk):
    remove_user(pk)
    return HttpResponseRedirect(reverse('user_list'))


@cache_page(60 * 15)
def courses(request):
    courses_list = get_course_list()
    context = {'courses': courses_list}
    return render_to_response('user_manager/courses.html', context)

user_manager/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>vFob</title>
    {% block base_css %}
        <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "user_manager/css/base.css" %}" rel="stylesheet">
    {% endblock %}
    {% block css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-col navbar-fixed-top" role="navigation">
        <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'user_list' %}">Test to you</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'user_list' %}">Users</a></li>
                <li><a href="{% url 'courses' %}">Courses</a></li>
            </ul>
        </div>
        </div>
    </nav>

    <div class="container">
        <div class="starter-template">
        {% block content %}{% endblock %}
        </div>
    </div>
    {% block base_js %}
        <script src="{% static "jquery/jquery-3.1.0.min.js" %}"></script>
        <script src="{% static "jquery/jquery.cookie.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
        <script src="{% static "user_manager/js/base.js" %}"></script>
    {% endblock %}
    {% block js %}{% endblock %}
</body>
</html>

user_manager/templates/user_manager/courses.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
            <h2>COURSES</h2>
        </div>
    </div>
    <table class="table">
        <tr>
            <th>NAME</th>
            <th>CODE</th>
        </tr>
        {% for course in courses %}
        <tr class="text-left">
            <td>{{ course.name }}</td>
            <td>{{ course.code }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block css %}
    <link href="{% static "user_manager/css/courses.css" %}" rel="stylesheet">
{% endblock %}

user_manager/templates/user_manager/create_user.html
{% extends "base.html" %}
{% load staticfiles %}
{% load add_class%}


{% block content %}
    <div class="row">
        <div class="col-md-4">

            <a class="btn btn-danger btn-circle left-text" href="{% url 'user_list' %}">
                <i class="glyphicon glyphicon-menu-left"></i>
            </a>
        </div>
        <div class="col-md-4">
            <h2>CREATE USER</h2>
        </div>
        <div class="col-md-2 col-md-offset-2">
            <p class="btn btn-default round btn-message hidden" id="response"></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-4">
            <form class="create_user" id="form_create_user" action="" method="post" role="form">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_name"><span class="red">*</span> Name</label>
                        {{ form.name|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_email"><span class="red">*</span>Email</label>
                        {{ form.email|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_phone">Phone</label>
                        {{ form.phone|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_mobile">Mobile phone</label>
                        {{ form.mobile|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_status">Status</label>
                        {{ form.status|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <input class="btn btn-success round right-text" id="create_user" type="button" value="Create">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block css %}
    <link href="{% static "user_manager/css/create_user.css" %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static "user_manager/js/create_user.js" %}"></script>
{% endblock %}

user_manager/templates/user_manager/edit_user.html
{% extends "base.html" %}
{% load staticfiles %}
{% load add_class%}

{% block content %}
    <div class="row">
        <div class="col-md-4">
            <a class="btn btn-danger btn-circle left-text" href="{% url 'user_list' %}">
                <i class="glyphicon glyphicon-menu-left"></i>
            </a>
        </div>
        <div class="col-md-4">
            <h2>CHANGE USER</h2>
        </div>
        <div class="col-md-2 col-md-offset-2">
            <p class="btn btn-default round btn-message hidden" id="response"></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-4">
            <form class="edit_user" id="form_edit_user" action="" method="post">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_name"><span class="red">*</span> Name</label>
                        {{ form.name|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_email"><span class="red">*</span>Email</label>
                        {{ form.email|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_phone">Phone</label>
                        {{ form.phone|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_mobile">Mobile phone</label>
                        {{ form.mobile|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label for="id_status">Status</label>
                        {{ form.status|add_class:"form-control round" }}
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label class="left-text" for="id_courses">Courses</label>
                        {{ form.courses|add_class:"hidden"}}
                        <div id="selector_courses" class="row">
                            <div class="col-md-10"></div>
                            <div class="col-md-2">
                                <a id="add_course" class="btn btn-success btn-circle left-text">
                                    <i class="glyphicon glyphicon-plus"></i>
                                </a>
                            </div>
                        </div>
                        <table class="table">
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="col-md-6 error-text"></div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <input class="btn btn-success round right-text" id="edit_user" type="button" value="Save">
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block css %}
    <link href="{% static "user_manager/css/edit_user.css" %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static "user_manager/js/edit_user.js" %}"></script>
{% endblock %}

user_manager/templates/user_manager/user_list.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
    <div class="row">
        <div class="col-md-5">
            <form class="form-inline left-text" method="GET">
                <a class="btn btn-danger btn-circle"  href="{% url 'create_user' %}">
                    <i class="glyphicon glyphicon-plus"></i>
                </a>
                <button class="btn btn-success btn-circle search-input-icon">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
                <input id="search-input" class="form-control round search-input" type="text" name="search" value="{{ search }}">
            </form>
        </div>
        <div class="col-md-2">
            <h2>USERS</h2>
        </div>
        <div class="col-md-4">

        </div>
        <div class="col-md-1">
            <select class="form-control input-sm round " id="row_count">
                <option {% if row_count == '10' %} selected {% endif %} value="10">10</option>
                <option {% if row_count == '15' %} selected {% endif %} value="15">15</option>
                <option {% if row_count == '20' %} selected {% endif %} value="20">20</option>
            </select>
        </div>
    </div>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        {% for user in users %}
        <tr class="text-left">
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
            <td>
                {% if user.status %}
                    <span class="green">Active</span>
                {% else %}
                    <span class="red">Inactive</span>
                {% endif %}
            </td>
            <td>
                <a href="{% url 'edit_user' user.id %}">
                    <i class="glyphicon glyphicon-pencil"></i></a>
                <a  href="{% url 'delete_user' user.id %}">
                    <i class="glyphicon glyphicon-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% if paginator.has_next %}
        <ul class="pagination">
        {% if paginator.has_previous %}
            <li><a href="?page={{ paginator.previous_page_number }}{% if search %}&search={{ search }}{% endif %}">
                <i class="glyphicon glyphicon-menu-left"></i></a></li>
        {% else %}
            <li class="disabled"><a><i class="glyphicon glyphicon-menu-left"></i></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
            <li {% if paginator.current_page == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
        {% endfor %}
        {% if paginator.has_next %}
            <li><a href="?page={{ paginator.next_page_number }}{% if search %}&search={{ search }}{% endif %}">
                <i class="glyphicon glyphicon-menu-right"></i></a></li>
        {% else %}
            <li class="disabled"><a><i class="glyphicon glyphicon-menu-right"></i></a></li>
        {% endif %}
        </ul>
    {% endif %}
{% endblock %}

{% block css %}
    <link href="{% static "user_manager/css/user_list.css" %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static "user_manager/js/user_list.js" %}"></script>
{% endblock %}